spring:

  application:
    name: eCrimePortal

  datasource:
    url: jdbc:mysql://localhost:3306/ecrimeportaldb
    username: root
    password: abhiyadav1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


    security:
      user:
        name: abhishek
        password: 123456